"""Initial migration

Revision ID: 964f7d696e24
Revises: 
Create Date: 2025-09-28 11:40:25.447080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964f7d696e24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
